version: '3.7'

services:
  spotishare:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    container_name: spotishare
    env_file:
      - .env
    ports:
      - '5000:5000'
    command: npm run dev
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env
    ports: 
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  node_modules:
  postgres: