version: '3.7'

services:
  spotishare:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    container_name: spotishare
    env_file:
      - .env
    ports:
      - '5000:5000'
    command: npm run dev

volumes:
  node_modules: