version: '3.7'

services:
  spotishare:
    image: 794948722843.dkr.ecr.eu-central-1.amazonaws.com/spotishare:latest
    env_file:
      - .env
    expose:
      - '5000'
    ports:
      - '5000:5000'
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
       npx prisma migrate deploy
       npx prisma generate
       npm start
  db:
    image: postgres
    env_file:
      - .env
    ports: 
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: