version: '3.7'

services:
  spotishare:
    image: 794948722843.dkr.ecr.eu-central-1.amazonaws.com/spotishare:latest
    env_file:
      - .env
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: npm start